---
title: "LabN"
author: "Kate Brandt"
date: "March 28, 2019"
output: pdf_document
---

## Q1. Reduced form Model:

  $$y_{ij} = B_{11} + B_{12} coa + B_{13} peer + B_{21}t{ij} + B_{22}coa t_{ij} + B_{23}peer t_{ij} + \zeta_{1j} + \zeta_{2j}t_{ij} + \epsilon_{ij}$$ 


## Q2. Interpret the coefficients

  $\eta_{1j}$ = The model for the intercept of "alcohol use" ($y_{ij}$) at age 14, as a function of two variables: child of an alcoholic and peer alcohol use. $\gamma_{11}$ represents the intercept for this equation (age), and the other two variables represent the two input variables. The random effects term is represented by $\zeta_{1j}$. The subscript "1" represents the inital cross section of data; subscript "j" represents the individual. 
  
  $\eta_{2j}$ = The model for the growth rate of alcohol use based on cross sectional data at the second time point. The terms all represent the same things, substantively, as the first equation, but the subscript "2" represents a later time point of the data colleciton. In the full equation, each term is multiplied by the time term, $t_{ij}$ to get the trajectory of these varibles and how they have changed relative to age; this part is important because it ensures there is a trajectory being modeled instead of finding differences (like in a random effects model). 
  
  
## Q3. Fit the model by restricted maximum likelihood

```{r, warning = FALSE, message = FALSE}
library(readstata13)
library(dplyr)
library(tidyverse)
library(lme4)
library(plm)

alcuse <- read.dta13("./data/alcuse.dta")
head(alcuse)

# Create interaction variables
alcuse$coa_t <- alcuse$coa*alcuse$age_14
alcuse$peer_t <- alcuse$peer*alcuse$age_14


mod.growth <- lmer(alcuse ~ age + male + coa + peer + coa_t + peer_t + (1 + age_14 | id), data=alcuse)
summary(mod.growth)

```

